name: Go CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:    
    - uses: actions/checkout@v2
    - uses: actions/setup-go@v2
      with:
          go-version: '1.16.3'
    - name: Install dep
      run: |  
        go get -u github.com/golang/dep/cmd/dep
        dep ensure
    - name: Build and analyze
      run: ./go.test.sh
    - name: Codecov
      run: curl -s https://codecov.io/bash | bash
