name: Go CI build

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:    
    - uses: actions/checkout@v2
    - uses: actions/setup-go@v2
      with:
          go-version: '1.17.7'
    - name: Build and analyze
      run: ./go.test.sh
    - name: Codecov
      uses: codecov/codecov-action@v2
