name: Go CI build

on:
  workflow_call:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version: "1.19.2"
      - name: Build and analyze
        run: make
      - name: Codecov
        uses: codecov/codecov-action@v5
