name: JS CI build

on:
  workflow_call:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: "16"
          cache: "pnpm"
          cache-dependency-path: client/pnpm-lock.yaml
      - name: Build and test
        run: |
          cd client
          pnpm install
          pnpm test:ci
