name: Pull Request

on:
  pull_request:
    branches: [ master ]    

jobs:
  go:
    uses: ./.github/workflows/go.yml
  js:
    uses: ./.github/workflows/js.yml    
  automerge:
    needs: 
      - go
      - js
    uses: ./.github/workflows/automerge.yml
