name: Release

on:
  push:
    tags:
      - "v*"

jobs:
  client:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v4
        with:
          version: 7
      - uses: actions/setup-node@v3
        with:
          node-version: "18"
          cache: "pnpm"
          cache-dependency-path: client/pnpm-lock.yaml
      - name: Build
        run: |
          cd client
          pnpm install
          pnpm build
      - name: Upload client
        uses: actions/upload-artifact@v4
        with:
          name: client
          path: client/build/**
          retention-days: 1
  build:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        arch: [amd64, arm, arm64]
        exclude:
          - os: ubuntu-latest
            arch: arm64
          - os: macos-latest
            arch: arm
          - os: windows-latest
            arch: arm
          - os: windows-latest
            arch: arm64
        include:
          - os: ubuntu-latest
            arch: arm
            arm: 5
    runs-on: ${{ matrix.os }}
    needs: client
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version: "1.19.2"
      - name: Download client
        uses: actions/download-artifact@v4.1.7
        with:
          name: client
          path: client/build
      - name: Install package
        run: sudo apt-get -y install gcc-arm-linux-gnueabi
        if: ${{ matrix.os == 'ubuntu-latest' }}
      - name: Build
        run: make build VERSION=$GITHUB_REF_NAME GOARCH=${{ matrix.arch }} GOARM=${{ matrix.arm }}
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          path: go-foosball*
          retention-days: 1
  release:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Download artifacts
        uses: actions/download-artifact@v4.1.7
      - uses: "marvinpinto/action-automatic-releases@v1.2.1"
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          prerelease: false
          files: |
            **/go-foosball*
