name: Release

on:
  push:
    tags:        
      - 'v*'   

jobs:
  build:

    runs-on: ubuntu-latest

    steps:    
    - uses: actions/checkout@v2
    - uses: actions/setup-go@v2
      with:
          go-version: '1.19.2'
    - uses: actions/setup-node@v2
      with:
        node-version: '16'
    - name: Build client
      run: make client version=${env:GITHUB_REF_NAME}
    - name: Build Linux
      run: make build-linux version=${env:GITHUB_REF_NAME}
    - name: Build Windows
      run: make build-windows version=${env:GITHUB_REF_NAME}
    - name: Build MacOS
      run: make build-darwin-arm version=${env:GITHUB_REF_NAME}
    - uses: "marvinpinto/action-automatic-releases@v1.2.1"
      with:
        repo_token: "${{ secrets.GITHUB_TOKEN }}"
        prerelease: false
        files: |
            LICENSE
            go-foosball*