name: Release

on:
  push:
    tags:        
      - 'v*'   

jobs:
  build:

    runs-on: ubuntu-latest

    steps:    
    - uses: actions/checkout@v2
    - uses: actions/setup-go@v2
      with:
          go-version: '1.19.2'
    - uses: actions/setup-node@v2
      with:
        node-version: '16'
    - name: Build and release
      run: make client build