name: Release

on:
  push:
    tags:
      - "v*"

jobs:
  client:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: "16"
          cache: "yarn"
      - name: Build
        run: |
          cd client 
          yarn build
      - name: Upload client
        uses: actions/upload-artifact@v3
        with:
          name: client
          path: client/build/**
  build:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    needs: client
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v3
        with:
          go-version: "1.19.2"
      - name: Download client
        uses: actions/download-artifact@v3
        with:
          name: client
          path: client/build
      - name: Build
        run: make build VERSION=$GITHUB_REF_NAME
      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          path: go-foosball*
          retention-days: 1
  release:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Download artifacts
        uses: actions/download-artifact@v3
      - uses: "marvinpinto/action-automatic-releases@v1.2.1"
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          prerelease: false
          files: |
            **/go-foosball*
